language: rust
sudo: false

rust:
  - 1.6.0
  - stable
  - beta
  - nightly

script:
  - cargo test
  - |
      if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
         cargo install --git https://github.com/arcnmx/cargo-clippy
         cargo clippy --lib --features lints
         cargo clippy --bin gpio --features lints
      fi
  - cargo doc
