[package]
name = "gpio-utils"
version = "0.1.0"
authors = ["Paul Osborne <osbpau@gmail.com>"]

[dependencies]
clap = "2.2"
rustc-serialize = "0.3"
sysfs_gpio = "0.4"
toml = "0.1"
glob = "0.2"
log = "0.3"
env_logger = "0.3"

[dependencies.clippy]
version = "0.0"
optional = true

[features]
default = []
lints = ["clippy"]

[[bin]]
name = "gpio"
path = "src/main.rs"
